theme = "catppuccin_mocha"

[editor]
line-number = "relative"
bufferline = "always"
auto-save = true
color-modes = true
# mouse = false

[editor.lsp]
display-inlay-hints = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
tab = [":w", ":bn"]
S-tab = [":w", ":bp"]


[editor.cursor-shape]
insert = "bar"